//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicePose.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPicture
    {
        public int id { get; set; }
        public int userID { get; set; }
        public string url { get; set; }
        public double Point { get; set; }
        public int TotalRated { get; set; }
        public System.DateTime uploadedDate { get; set; }
        public string templateLink { get; set; }
        public bool isActive { get; set; }
    
        public virtual NiceposeUser NiceposeUser { get; set; }
    }
}
